services:
  clientemqtt:
    build: ./clienteMqtt #aca busca la imagen en la carpeta clienteMqtt
    init: true
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - PYTHONUNBUFFERED=1

      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR}
      - TOPICO_1=${TOPICO_1}
      - TOPICO_2=${TOPICO_2}
      - TOPICO_3=${TOPICO_3}

    restart: unless-stopped